# Project information
site_name: 'scrcast'
site_description: 'Your drop in screen recording solution on Android'
site_author: 'bmcreations'
site_url: 'https://bmcreations.dev'
remote_branch: gh-pages

# Repository
repo_name: 'scrcast'
repo_url: 'https://github.com/bmc08gt/scrcast'

# Copyright
copyright: 'Copyright &copy; 2020 bmcreations'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Navigation
nav:
  - 'Overview': index.md
  - 'API':
      - 'scrcast': api/library/index.md
      - 'config': api/library/dev.bmcreations.scrcast.config/index.md
      - 'recorder': api/library/dev.bmcreations.scrcast.recorder/index.md
      - 'notifications': api/library/dev.bmcreations.scrcast.recorder.notification/index.md

# CSS
extra_css:
  - 'css/site.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
